SYSTEM     = x86-64_linux
LIBFORMAT  = static_pic

#------------------------------------------------------------
#
# When you adapt this makefile to compile your CPLEX programs
# please copy this makefile and set CPLEXDIR and CONCERTDIR to
# the directories where CPLEX and CONCERT are installed.
#
#------------------------------------------------------------

CPLEXDIR      = /net/cubitus/projects/Partage_ROC/Logiciels/CPLEX_Studio128/cplex
CONCERTDIR    = /net/cubitus/projects/Partage_ROC/Logiciels/CPLEX_Studio128/concert

# ---------------------------------------------------------------------
# Compiler selection 
# ---------------------------------------------------------------------

CCC = g++ -O0

# ---------------------------------------------------------------------
# Compiler options 
# ---------------------------------------------------------------------

CCOPT = -m64 -O -fPIC -fno-strict-aliasing -fexceptions -DNDEBUG -DIL_STD

# ---------------------------------------------------------------------
# Link options and libraries
# ---------------------------------------------------------------------

CPLEXBINDIR   = $(CPLEXDIR)/bin/$(BINDIST)
CPLEXJARDIR   = $(CPLEXDIR)/lib/cplex.jar
CPLEXLIBDIR   = $(CPLEXDIR)/lib/$(SYSTEM)/$(LIBFORMAT)
CONCERTLIBDIR = $(CONCERTDIR)/lib/$(SYSTEM)/$(LIBFORMAT)

CCLNDIRS  = -L$(CPLEXLIBDIR) -L$(CONCERTLIBDIR)
CLNDIRS   = -L$(CPLEXLIBDIR)
CCLNFLAGS = -lconcert -lilocplex -lcplex -lm -lpthread -ldl
CLNFLAGS  = -lcplex -lm -lpthread -ldl


CONCERTINCDIR = $(CONCERTDIR)/include
CPLEXINCDIR   = $(CPLEXDIR)/include

CCFLAGS = $(CCOPT) -I$(CPLEXINCDIR) -I$(CONCERTINCDIR)


BORWin: BORWin.o Graph.o
        $(CCC) $(CCOPT) bin/BORWin.o bin/Graph.o -o BORWin

BORWin.o: BORWin.cpp BORWin.h
        $(CCC) $(CCOPT) bin/BORWin.o bin/Graph.o -o BORWin

BORWin.o: BORWin.cpp BORWin.h
        $(CCC) -c $(CCOPT) BORWin.cpp -o bin/BORWin.o

Generator: Generator.o Graph.o
        $(CCC) $(CCOPT) bin/Generator.o bin/Graph.o -o Generator

Generator.o: Generator.cpp Generator.h
        $(CCC) -c $(CCOPT) Generator.cpp -o bin/Generator.o

Graph.o: Graph.cpp Graph.h
        $(CCC) -c $(CCFLAGS) $(CCLNDIRS) Graph.cpp -o bin/Graph.o


solveILP: solveILP.o Graph.o ILP.o
        $(CCC) $(CCFLAGS) $(CCLNDIRS) bin/solveILP.o  bin/Graph.o bin/ILP.o -o solveILP $(CCLNFLAGS)
solveILP.o: solveILP.cpp
        $(CCC) -c $(CCFLAGS) solveILP.cpp -o bin/solveILP.o
ILP.o: ILP.cpp ILP.h
        $(CCC) -c $(CCFLAGS) ILP.cpp -o bin/ILP.o
